openapi: 3.0.3
info:
  title: Flexgrid ATP API
  description: The Automated Trading Platform (ATP) of the flexgrid project
  termsOfService: https://atp.flexgrid-project.eu/terms/
  contact:
    name: Dimitros J. Vergados
    url: https://flexgrid-project.eu
  license:
    name: BSD
    url: https://github.com/pyeve/eve-swagger/blob/master/LICENSE
  version: "1.0"
servers:
- url: http://localhost:8080/
tags:
- name: Prosumer
paths:
  /stacked_revenues:
    post:
      tags:
      - StackedRevenues
      summary: Initiates a simulation scenario for Stacked Revenues maximization
      operationId: stacked_revenues_post
      requestBody:
        $ref: '#/components/requestBodies/StackedRevenuesParams'
      responses:
        "201":
          description: operation has been successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StackedRevenuesResult'
        "400":
          description: bad request
      security:
      - MyTokenAuth: []
      x-openapi-router-controller: swagger_server.controllers.stacked_revenues_controller
components:
  schemas:
    StackedRevenuesParams:
      required:
      - country
      - markets
      - sdate
      - storage_units
      type: object
      properties:
        sdate:
          type: string
          format: date
        country:
          type: string
        markets:
          minItems: 1
          type: array
          items:
            type: string
        storage_units:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/StorageUnit'
    StorageUnit:
      required:
      - location
      type: object
      properties:
        power_capacity_KW:
          minimum: 0
          type: number
        energy_capacity_KWh:
          minimum: 0
          type: number
        inefficiency_rate_per_cent:
          maximum: 1
          minimum: 0
          type: number
        initial_final_SoC_per_cent:
          maximum: 1
          minimum: 0
          type: number
        location:
          $ref: '#/components/schemas/Location'
    Location:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
          format: objectid
        name:
          type: string
    StackedRevenuesResult:
      required:
      - flex_offer
      - revenues
      - sdate
      type: object
      properties:
        sdate:
          type: string
          format: date
        flex_offer:
          $ref: '#/components/schemas/StackedRevenuesResultFlexOffer'
        revenues:
          $ref: '#/components/schemas/StackedRevenuesResultRevenues'
      example:
        sdate: 2000-01-23
        flex_offer:
          balancing_market_offer_down: null
          q-LMPs:
          - - price_unit: €/MVar
              volume_unit: MVar
              storage_unit: storage_unit
              values: null
            - price_unit: €/MVar
              volume_unit: MVar
              storage_unit: storage_unit
              values: null
          - - price_unit: €/MVar
              volume_unit: MVar
              storage_unit: storage_unit
              values: null
            - price_unit: €/MVar
              volume_unit: MVar
              storage_unit: storage_unit
              values: null
          reserve_market_offer_down: null
          balancing_market_offer_up: null
          day_ahead_market_offer:
            price_unit: €/MWh
            volume_unit: MWh
            values:
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
            - volume: 6.027456183070403
              price: 0.8008281904610115
          reserve_market_offer_up:
            price_unit: €/MWh^2
            volume_unit: MWh^2
            values: null
          d-LMPs:
          - - price_unit: €/MWh
              volume_unit: MWh
              storage_unit: storage_unit
              values: null
            - price_unit: €/MWh
              volume_unit: MWh
              storage_unit: storage_unit
              values: null
          - - price_unit: €/MWh
              volume_unit: MWh
              storage_unit: storage_unit
              values: null
            - price_unit: €/MWh
              volume_unit: MWh
              storage_unit: storage_unit
              values: null
        revenues:
          balancing_market_revenues: null
          reserve_market_revenues: null
          flexibility_market_revenues: null
          day_ahead_market_revenues:
            currency: €
            value: 1.4658129805029452
    DayOfferVector:
      maxItems: 25
      minItems: 23
      type: array
      items:
        $ref: '#/components/schemas/DayOfferVectorItem'
    DayOfferVectorItem:
      type: object
      properties:
        price:
          type: number
          format: currency
        volume:
          type: number
      example:
        volume: 6.027456183070403
        price: 0.8008281904610115
    DayOfferVectorEuroMWh:
      required:
      - price_unit
      - values
      - volume_unit
      type: object
      properties:
        values:
          $ref: '#/components/schemas/DayOfferVector'
        price_unit:
          type: string
          enum:
          - €/MWh
        volume_unit:
          type: string
          enum:
          - MWh
      example:
        price_unit: €/MWh
        volume_unit: MWh
        values:
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
        - volume: 6.027456183070403
          price: 0.8008281904610115
    Price_In_Euro:
      required:
      - currency
      - value
      type: object
      properties:
        value:
          type: number
        currency:
          type: string
          enum:
          - €
      example:
        currency: €
        value: 1.4658129805029452
    DayOfferVectorEuroMWh2:
      required:
      - price_unit
      - values
      - volume_unit
      type: object
      properties:
        values:
          $ref: '#/components/schemas/DayOfferVector'
        price_unit:
          type: string
          enum:
          - €/MWh^2
        volume_unit:
          type: string
          enum:
          - MWh^2
      example:
        price_unit: €/MWh^2
        volume_unit: MWh^2
        values: null
    FlexOfferDLMPs:
      type: array
      items:
        type: array
        items:
          $ref: '#/components/schemas/FlexOfferDLMPsItem'
    FlexOfferDLMPsItem:
      required:
      - price_unit
      - storage_unit
      - values
      - volume_unit
      type: object
      properties:
        storage_unit:
          type: string
        values:
          $ref: '#/components/schemas/DayOfferVector'
        price_unit:
          type: string
          enum:
          - €/MWh
        volume_unit:
          type: string
          enum:
          - MWh
      example:
        price_unit: €/MWh
        volume_unit: MWh
        storage_unit: storage_unit
        values: null
    FlexOfferQLMPs:
      type: array
      items:
        type: array
        items:
          $ref: '#/components/schemas/FlexOfferQLMPsItem'
    FlexOfferQLMPsItem:
      required:
      - price_unit
      - storage_unit
      - values
      - volume_unit
      type: object
      properties:
        storage_unit:
          type: string
        values:
          $ref: '#/components/schemas/DayOfferVector'
        price_unit:
          type: string
          enum:
          - €/MVar
        volume_unit:
          type: string
          enum:
          - MVar
      example:
        price_unit: €/MVar
        volume_unit: MVar
        storage_unit: storage_unit
        values: null
    StackedRevenuesResultFlexOffer:
      type: object
      properties:
        day_ahead_market_offer:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh'
        reserve_market_offer_up:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh2'
        reserve_market_offer_down:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh2'
        d-LMPs:
          $ref: '#/components/schemas/FlexOfferDLMPs'
        q-LMPs:
          $ref: '#/components/schemas/FlexOfferQLMPs'
        balancing_market_offer_up:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh'
        balancing_market_offer_down:
          $ref: '#/components/schemas/DayOfferVectorEuroMWh'
      example:
        balancing_market_offer_down: null
        q-LMPs:
        - - price_unit: €/MVar
            volume_unit: MVar
            storage_unit: storage_unit
            values: null
          - price_unit: €/MVar
            volume_unit: MVar
            storage_unit: storage_unit
            values: null
        - - price_unit: €/MVar
            volume_unit: MVar
            storage_unit: storage_unit
            values: null
          - price_unit: €/MVar
            volume_unit: MVar
            storage_unit: storage_unit
            values: null
        reserve_market_offer_down: null
        balancing_market_offer_up: null
        day_ahead_market_offer:
          price_unit: €/MWh
          volume_unit: MWh
          values:
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
          - volume: 6.027456183070403
            price: 0.8008281904610115
        reserve_market_offer_up:
          price_unit: €/MWh^2
          volume_unit: MWh^2
          values: null
        d-LMPs:
        - - price_unit: €/MWh
            volume_unit: MWh
            storage_unit: storage_unit
            values: null
          - price_unit: €/MWh
            volume_unit: MWh
            storage_unit: storage_unit
            values: null
        - - price_unit: €/MWh
            volume_unit: MWh
            storage_unit: storage_unit
            values: null
          - price_unit: €/MWh
            volume_unit: MWh
            storage_unit: storage_unit
            values: null
    StackedRevenuesResultRevenues:
      type: object
      properties:
        day_ahead_market_revenues:
          $ref: '#/components/schemas/Price_In_Euro'
        reserve_market_revenues:
          $ref: '#/components/schemas/Price_In_Euro'
        flexibility_market_revenues:
          $ref: '#/components/schemas/Price_In_Euro'
        balancing_market_revenues:
          $ref: '#/components/schemas/Price_In_Euro'
      example:
        balancing_market_revenues: null
        reserve_market_revenues: null
        flexibility_market_revenues: null
        day_ahead_market_revenues:
          currency: €
          value: 1.4658129805029452
  requestBodies:
    StackedRevenuesParams:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StackedRevenuesParams'
      required: true
  securitySchemes:
    MyTokenAuth:
      type: oauth2
      flows:
        password:
          tokenUrl: https://db.flexgrid-project.eu/oauth/token
          scopes: {}
        clientCredentials:
          tokenUrl: https://db.flexgrid-project.eu/authorization
          scopes:
            post_stacked_revenues: post a stacked revenues scenario
      x-tokenInfoFunc: swagger_server.controllers.authorization_controller.check_MyTokenAuth
      x-scopeValidateFunc: swagger_server.controllers.authorization_controller.validate_scope_MyTokenAuth

